### PR TITLE
Add entry on Celeste Kidd

### PR DESCRIPTION
**Pull request by LauraRuis**

### CODE REVIEW

**Review by ary — CHANGES_REQUESTED** [review]
Hi Laura! I appreciate your strong contribution. Please add new entries in alphabetical order (based on the last name). Thanks!

**Review by ary — CHANGES_REQUESTED** [review]
Please order alphabetically by last name, thanks!

Edit: just saw your newest commit, apologies.

**Comment by LauraRuis** [comment]
You know what it doesn't surprise me that I needed 3 commits for this. Welcome to a preview of what it's like to work with me.

**Comment by ary** [comment]
> Welcome to a preview of what it's like to work with me.

I don't see the issue, I'd gladly work with you any time <3

**Pull request merged**
