### PR TITLE
Add mission street and market street

### PR DESCRIPTION
**Pull request by lorenzkuhn**

### CODE REVIEW

**Comment by lorenzkuhn** [comment]
cc @kklein

**Comment by kklein** [comment]
Stretching it @lorenzkuhn!

**Comment by ary** [comment]
Thank you for your contribution @lorenzkuhn. It is with great regret that I have to inform you I cannot accept your proposed changes. [Dictionary.com defines aptonym](https://www.dictionary.com/browse/aptonym) to be "a name that is particularly well suited to the nature, career, or other personal characteristics of the person so named". Your proposed additions to the list do not, according to this definition, qualify as aptonyms.

**Comment by lorenzkuhn** [comment]
😿

**Pull request closed without merging**
